replicaCount: 2

image:
  repository: nasrullah125/welcome-site
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  host: welcome.local

resources: {}
