apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: welcome-nginx
  namespace: argocd   # <-- Add this

spec:
  project: default

  source:
    repoURL: https://github.com/itxnk/welcome-site.git
    targetRevision: main
    path: helm/welcome

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
